services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./data/kafka:/kafka # data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: hlam
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: storage
    ports:
      - "3307:3306"
    volumes:
    # Where our data will be persisted
      - ./data/database:/var/lib/mysql # data folder
  receiver:
    build:
      context: receiver
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - storage
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./config/receiver:/app/config:r # config folder
      - ./logs/receiver:/app/logs:rw # logs folder
  storage:
    restart: always
    build:
      context: storage
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
      kafka:
        condition: service_healthy
    ports:
      - "8090:8090"
    expose:
      - "8090"
    volumes:
      - ./config/storage:/app/config:r # config folder
      - ./logs/storage:/app/logs:rw # logs folder
  processing:
    build:
      context: processing
      dockerfile: Dockerfile
    depends_on:
      - storage
    ports:
      - "8100:8100"
    expose:
      - "8100"
    volumes:
      - ./data/processing:/app/data:rw # data folder
      - ./config/processing:/app/config:r # config folder
      - ./logs/processing:/app/logs:rw # logs folder
  analyzer:
    build:
      context: analyzer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - storage
    ports:
      - "8110:8110"
    expose:
      - "8110"
    volumes:
      - ./config/analyzer:/app/config:r # config folder
      - ./logs/analyzer:/app/logs:rw # logs folder

# # Defines a named volume
# volumes:
#   my-db:
