openapi: 3.0.0
info:
  title: Check Service API
  description: Provides the status of your services
  version: "1.0.0"
  contact:
    email: hlam101@my.bcit.ca
paths:
  /update:
    put:
      summary: Update the check datastore
      operationId: app.check_services
      description: Updates the check datastore by querying the other services
      responses:
        '201':
          description: Successfully updated the check datastore
          content:
            application/json:
              schema:
                type: object
                properties:
                  service_count:
                    type: integer
                    example: 4
  /check:
    get:
      operationId: app.get_checks
      responses:
        "200":
          description: OK - stats returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Check"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Check:
      required:
        - receiver
        - storage
        - processing
        - analyzer
      properties:
        receiver:
          type: string
          example: "Healthy at 2025-12-12 9:34:56"
        storage:
          type: string
          example: "Storage has 6 Volume and 4 Type events"
        processing:
          type: string
          example: "Processing has 6 Volume and 4 Type events"
        analyzer:
          type: string
          example: "Analyzer has 10 Volume and 4 Type events"
